### PR TITLE
Create jqModal.d.ts for support TypeScript

### PR DESCRIPTION
**Pull request by Hooter**

### CODE REVIEW

**Comment by briceburg** [comment]
@hooter this is great and sets our API in stone. Do you think this is good to ship as is? LGTM, although I think it also mandates tests to ensure config matches ts definition

**Comment by Hooter** [comment]
@briceburg it's work :) We use your code to us project. And last time migrate to TypeScript for new code. Today I wrote this code, for support this plugin.

If You want, I can add code for support Accessebility for this modal dialog.

**Comment by briceburg** [comment]
@hooter I hear you. Tests are easier to keep up when they exist in the
first place. I'll put it on my to-do. Many thanks for this contribution!
Awesome work.

**Comment by briceburg** [comment]
BTW, this was this first PR I've merged while helming a sailboat!

**Pull request merged**
